# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-14 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mugsandcups', '0004_cupssection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CupsSection',
        ),
    ]
