# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mugsandcups', '0006_auto_20160514_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='client_logo',
            new_name='catalog_image',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='src',
        ),
    ]
