# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugsandcups', '0007_auto_20160514_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('feature_image', models.FileField(upload_to='')),
            ],
        ),
    ]
