# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mugsandcups', '0008_featured'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Featured',
            new_name='Feature',
        ),
    ]
